### ISSUE TITLE
Sometimes additional fields appear in the Compare table.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vsf-default#13]
## Current behavior
Sometimes additional fields appear in the Compare table and  description contains  < p > tag

![image](https://user-images.githubusercontent.com/36628922/83152828-8911bd80-a0fe-11ea-9f3c-cfab0ac5bb0a.png)

## Expected behavior
Do not display unneeded fields and remove < p > tag

![image](https://user-images.githubusercontent.com/36628922/83152845-8f079e80-a0fe-11ea-99c3-1af841d817d5.png)

## Steps to reproduce the issue
1. Add products to compare
2. Remove any product
3. Go to any PDP and add the product to Compare list again
4. Open the Compare list
5. Repeat steps if necessary

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by AdamPawlinski** [comment]
@alinadivante I could not reproduce this bug, is it still appearing? If so, please let me know how to reproduce. Thanks.

![Peek 2020-10-20 09-26](https://user-images.githubusercontent.com/32042425/96554162-7323b580-12b6-11eb-9233-58aab1df5499.gif)

**Comment by Fifciu** [comment]
We are waiting for @alinadivante to recheck this
