### ISSUE TITLE
Iphone - scroll doesn't work in search tab

### ISSUE THREAD

**Issue by gibkigonzo** [DivanteLtd/vsf-default#18]
## Current behavior

![Image from iOS](https://user-images.githubusercontent.com/42383376/83997922-cd535800-a95f-11ea-8830-2a6009eb1deb.png)
User can't scroll in search tab on iphone

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Fifciu** [comment]
@lukaszjedrasik will take care of that at 11th Nov 2020

**Comment by lukaszjedrasik** [comment]
### Step to reproduce

Device: iPhone XS Max
OS: iOS 14.2

1. Open Search Panel and type eg. `yoga`
2. Close Search Panel
3. Open and close other Sidebar eg. Menu 
4. Open Search Panel and type eg. `yoga`. Now scroll shouldn't work
