### ISSUE TITLE
add capybara theme

### ISSUE THREAD

**Issue by gibkigonzo** [DivanteLtd/vsf-default#20]
## What is the motivation for adding/enhancing this feature?

It would be nice to add information about capybara theme to default. Maybe as popup :shrug: 

## What are the acceptance criteria?

- [ ] - user can see information about capybara theme and can easily remove it

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Fifciu** [comment]
We could do it when Capybara becomes Production Ready - right now we have to wait
