### ISSUE TITLE
newsletterpopup dose not show after setting it to true

### ISSUE THREAD

**Issue by qasmmaoui** [DivanteLtd/vsf-default#21]
HEllo , 
i need to show newsletterpopup modal after certain amount of time , 
i enabled it in module/ui-store/index.ts but it dose not show up.
any help would be apreciated.

Thank you in advance 

Brest regards

**Comment by gibkigonzo** [comment]
hey @qasmmaoui I've moved this issue to theme repo. It works on https://demo.storefrontcloud.io/ so I can't help you without code

**Comment by Fifciu** [comment]
Hello @qasmmaoui, as you are inactive since few months I am going to close this issue. Contact us, if you can show us the code - so we would reopen the issue be able to help you.
