### ISSUE TITLE
[Bug] iOS - after selecting 'sort by' side swipe is possible

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vsf-default#24]
## Current behavior
On iOS after selecting 'sort by' option the page is zoomed and side swipe is possible.

## Expected behavior
There should not be possibility to side swipe the page after selecting 'sort by' option.

## Steps to reproduce the issue
1. go to any category page on iOS
2. press 'Latest' on the top of the page
3. select low to high or high to low and press 'done'
4. try to side swipe and see the error

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details
iOS

## Additional information
![SideSwipeiOS](https://user-images.githubusercontent.com/57936972/88161465-4d800500-cc10-11ea-9388-1eaf2428ab2f.gif)

**Comment by Fifciu** [comment]
@lukaszjedrasik will take care of that at 11th Nov 2020
