### ISSUE TITLE
[Bug] iOS- filter option is not working correctly

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vsf-default#25]
## Current behavior
On iOS after selecting filter option and pressing the 'Filter' button the tab is not closing and user needs to scroll up in order to close it

## Expected behavior
After selecting filter option and pressing 'Filter' button the tab should close and list of filtered products should appear

## Steps to reproduce the issue
1. go to any product listing page on iOS
2. press 'Filter'
3. select any filter option
4. scroll down to the 'Filter' button and press it
5. see the error

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details
iOS
## Additional information
![FilteriOS](https://user-images.githubusercontent.com/57936972/88162872-2de9dc00-cc12-11ea-86e1-85fe9faa00d9.gif)

**Comment by Fifciu** [comment]
@lukaszjedrasik will take care of that
