### ISSUE TITLE
After selecting a category in the search results, all results disappear.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vsf-default#6]
## Current behavior
When you select a category in the search results, all results disappear.
![image](https://user-images.githubusercontent.com/36628922/82900444-d22a0c00-9f5c-11ea-9b3a-323e71ede31c.png)
![image](https://user-images.githubusercontent.com/36628922/82900456-d7875680-9f5c-11ea-8f93-d1f22936d74d.png)

## Expected behavior
Results should be visible.

## Steps to reproduce the issue
1. Open search bar
2. Press `top`
3. Select one of categories, e.g `Bras & Tanks`

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by gibkigonzo** [comment]
fixed, problem was with invalid data in ES
