### ISSUE TITLE
It is not possible to order virtual products via Instant checkout.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vsf-default#8]
## Current behavior
It is not possible to order virtual products via Instant checkout.
Following errors in dev console:

![image](https://user-images.githubusercontent.com/36628922/83120361-3f5eae00-a0d1-11ea-90cf-77b9142fe090.png)

## Note:
Instant Checkout  is not available on demo..

## Expected behavior
Users should be able to place an order via instant checkout.

## Steps to reproduce the issue
1. Add virtual product to the cart
2. Open cart
3. Press `Instant Checkout` 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by gibkigonzo** [comment]
fixed by https://github.com/DivanteLtd/vue-storefront/pull/4480
